version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: graft_user
      POSTGRES_PASSWORD: graft_password
      POSTGRES_DB: graft_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
